#+TITLE: Systematik der geschichtswissenschaftlichen Bibliotheken
* Maschinenschriftliche Vorlagen

[[https://www.uni-heidelberg.de/md/zegk/histsem/seminar/systematik_hs.pdf][Maschinenschriftliche Systematik des Historischen Seminars]]

[[https://www.uni-heidelberg.de/md/zegk/histsem/seminar/systematik_fpi.pdf][Maschinenschriftliche Systematik des Instituts für Fränkisch-Pfälzische Geschichte und Landeskunde]]

[[https://www.uni-heidelberg.de/md/zegk/histsem/seminar/systematik_schurman.pdf][Systematik der Schurman Bibliothek]]

* Formatierung

Die Formatierung der Systematiken verwendet die vereinfachte Auszeichnungssprache, die [[https://orgmode.org/guide/Markup.html#Markup][Org-Mode]] für Emacs zugrunde liegt. 

#+BEGIN_SRC
,* Bibliothek
,** A - Titel Ebene 1
,*** Ac - Titel Ebene 2
,**** 0000 - 1234 Titel Ebene 3
,***** 0000 - 0234 Titel Ebene 4
,***** 0235 - 1234 Titel Ebene 4
,**** 1235 - 1300 Titel Ebene 3
,***** 1235 - 1250 Titel Ebene 4
,***** 1251 - 1300 Titel Ebene 4
#+END_SRC

Zum Beispiel:

#+BEGIN_SRC
,* Historisches Seminar
,** A - Hilfsmittel und Hilfswissenschaften, EDV-Literatur, Neue Medien
,*** Ac - Historische Geographie
,**** 0001 - 00700 Atlanten
,***** 0001 - 0030 Allgemeine geographische Atlanten
,***** 0031 - 0150 Allgemeine historische Atlanten
,***** 0151 - 0250 Historische Atlanten, zeitlich begrenzt
,***** 0251 - 0400 Historische Atlanten, räumlich begrenzt
,***** 0401 - 0600 Historische Atlanten, Deutschland (gesamt und regional)
,***** 0601 - 0700 Systematische Atlanten
,**** 0701 - 0750 Einführungen, Allgemeines
,**** 0751 - 0900 Allgemeine historische geographische Darstellungen
,**** 0901 - 1050 Historische Landschaftskunde
,**** 1051 - 1300 Systematische Siedlungskunde
,***** 1051 - 1150 Anthropogeographie
,***** 1151 - 1300 Historische Bevölkerungs- und Siedlungskunde
,**** 1301 - 1600 Historisch politische Geographie
,***** 1301 - 1400 Allgemeine systematische Darstellungen
,***** 1401 - 1500 Größere Darstellungen und Werke
,***** 1501 - 1600 Spezialdarstellungen
,**** 1601 - 1800 Topographie
,***** 1601 - 1700 Orts- und Landeskunde
,***** 1701 - 1800 Namenkunde
,**** 1801 - 1999 Kartographie
#+END_SRC

* Bearbeitungsstatus der einzelnen Signaturgruppen

Die Systematiken der Bibliotheken bilden insgesamt knapp 10.000 Zeilen - eine erhebliche Menge. Um den Status der jeweiligen alphabetischen Signaturgruppen in Ordnung zu halten, bitte schreiben Sie (in großen Buchstaben) entweder ~TODO~ oder ~DONE~ wie unten dargestellt. Sind z.B. alle untergeordnete Signaturen einer Gruppe bearbeitet worden, dann sollte ein ~TODO~ zu einem ~DONE~ in dem sogenanntent parent heading. 

Zum Beispiel: 

#+BEGIN_SRC
,* TODO Historisches Seminar
,** TODO A - Hilfsmittel und Hilfswissenschaften, EDV-Literatur, Neue Medien
,*** TODO Ac - Historische Geographie
,** TODO B - Quellen zur Geschichte des Mittelalters
,*** TODO Bf - Papsturkunden
#+END_SRC

vs. 

#+BEGIN_SRC
,* TODO Historisches Seminar
,** DONE A - Hilfsmittel und Hilfswissenschaften, EDV-Literatur, Neue Medien
,*** DONE Ac - Historische Geographie
,** TODO B - Quellen zur Geschichte des Mittelalters
,*** TODO Bf - Papsturkunden
#+END_SRC

